# Site settings
title: Weekly AI News
description: >- # this means to ignore newlines until "baseurl:"
  毎週更新！一週間分のAIニュースをコンパクトにお届けします。
baseurl: "/weekly_ainews" # ★ここを修正！
url: "https://kzkzkn/weekly_AInews.github.io"
github_username: kzkzkn

# Build settings
theme: minima
plugins:
  - jekyll-feed
# You can add more configuration options here
