# Site settings
title: Weekly AI News
description: >- # this means to ignore newlines until "baseurl:"
  毎週更新！一週間分のAIニュースをコンパクトにお届けします。
baseurl: "" # the subpath of your site, e.g. /blog. If hosted at the root, leave it empty.
url: "https://kzkzkn.github.io" # ★ここを修正！
github_username: kzkzkn             # ★ここを修正！

# Build settings
theme: minima # Jekyllのデフォルトテーマ。デザインをカスタマイズしない場合はこのままでOK。
plugins:
  - jekyll-feed

# You can add more configuration options here
